apiVersion: v1
kind: Pod
metadata:
  name: xyzapp
  namespace: default
  labels:
    app: demo
spec:
  containers:
  - name: xyz-container
    image: hristyle06/xyz_tech:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xyzsvc
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
