version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Building the Java application"
      - mvn package -DskipTests=true
      - echo "List target directory"
      - ls -R target

  pre_build:
    commands:
      - echo "Running pre-build steps"
      - mvn clean

  build:
    commands:
      - echo "Building the Java application"
      - mvn package -DskipTests=true

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Copying artifacts"
      - echo "Build complete. Listing all files:"
      - find . -type f

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*

  discard-paths: yes
i
