version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies"
      - mvn install -DskipTests=true

  pre_build:
    commands:
      - echo "Running pre-build steps"
      - mvn clean

  build:
    commands:
      - echo "Building the Java application"
      - mvn package -DskipTests=true

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Copying artifacts"

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: yes

